import 'dart:async';

import 'package:floor/floor.dart';
import 'package:meme_app/dao/meme_dao.dart';
import 'package:meme_app/entity/meme.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

part 'app_database.g.dart'; // This file will be generated by Floor

@Database(version: 1, entities: [Meme])
abstract class AppDatabase extends FloorDatabase {
  MemeDao get memeDao;
}
